[pytest]
filterwarnings =
    ignore::DeprecationWarning:anyio._lazyimport
    ignore::DeprecationWarning:starlette.testclient
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::DeprecationWarning:starlette._utils
    ignore::DeprecationWarning:pydantic.fields
    ignore::DeprecationWarning:pydantic._internal._config
