-- Predict IQ staging schema. This file creates structure only; it inserts no data.

create table if not exists machines (
    id bigint generated by default as identity primary key,
    machine_id varchar(50) not null unique,
    name varchar(100) not null,
    type varchar(100) not null,
    location varchar(150) not null,
    status varchar(50) not null default 'Healthy',
    created_at timestamptz not null default now()
);

create table if not exists devices (
    id bigint generated by default as identity primary key,
    device_id varchar(100) not null unique,
    machine_id varchar(50) not null references machines(machine_id) on delete cascade,
    device_type varchar(100) not null default 'ESP32',
    firmware_version varchar(50) not null default '1.0.0',
    status varchar(20) not null default 'OFFLINE',
    last_seen timestamptz,
    source varchar(30) not null,
    created_at timestamptz not null default now()
);

create table if not exists sensor_readings (
    id bigint generated by default as identity primary key,
    machine_id varchar(50) not null references machines(machine_id) on delete cascade,
    device_id varchar(100) not null references devices(device_id) on delete cascade,
    timestamp timestamptz not null,
    temperature double precision not null,
    vibration double precision not null,
    current double precision not null,
    rpm double precision not null,
    source varchar(30) not null,
    created_at timestamptz not null default now()
);

create table if not exists maintenance_records (
    id bigint generated by default as identity primary key,
    machine_id varchar(50) not null references machines(machine_id) on delete cascade,
    component varchar(100) not null,
    failure_type varchar(100),
    issue_description text not null,
    maintenance_action text not null,
    technician varchar(100) not null,
    status varchar(50) not null default 'Scheduled',
    failure_date timestamptz,
    maintenance_date timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create table if not exists alerts (
    id bigint generated by default as identity primary key,
    machine_id varchar(50) not null references machines(machine_id) on delete cascade,
    alert_type varchar(100) not null,
    severity varchar(50) not null default 'Warning',
    message text not null,
    status varchar(50) not null default 'ACTIVE',
    created_at timestamptz not null default now(),
    resolved_at timestamptz
);

create table if not exists predictions (
    id bigint generated by default as identity primary key,
    machine_id varchar(50) not null references machines(machine_id) on delete cascade,
    timestamp timestamptz not null,
    failure_probability double precision,
    component varchar(100),
    remaining_life_days integer,
    confidence double precision,
    explanation text,
    recommended_action text,
    model_version varchar(100),
    created_at timestamptz not null default now()
);

create index if not exists ix_devices_machine_id on devices(machine_id);
create index if not exists ix_sensor_readings_machine_id on sensor_readings(machine_id);
create index if not exists ix_sensor_readings_device_id on sensor_readings(device_id);
create index if not exists ix_sensor_readings_timestamp on sensor_readings(timestamp);
create index if not exists ix_sensor_readings_machine_timestamp on sensor_readings(machine_id, timestamp);
create index if not exists ix_sensor_readings_device_timestamp on sensor_readings(device_id, timestamp);